### ISSUE TITLE
[QA] 0.9.0 Testplan

### ISSUE THREAD

**Issue by jnweiger** [owncloud/drawio#8]
## Test Plan drawio

The toplevel checkmark indictes the test was performed.
The indented checkmarks indicate the results were as expected.

This is a quick smoke test only. We don't test drawio itself, only the integration with ownCloud.

* [x] Enable the app
   * [x] No problems found
* [x] Disable and enable the app using CLI
   * [x] No problems found
* [x] Create a drawing file using the '+' button.
   * [x] A template dialog appears.
   * [x] An empty file with the suffix .drawio can be created created. 
   * [x] Multiple other templates are available, choosing one, a prepopulated drawing appears.
* [x] Save a drawing.
   * [x] The content of the file is updated in the server.
* [x] File locking
   * [x] Multiple users cannot open a drawing for editing simultaneously. -> #5
   * [ ] all additional users see a readonly view, as if through a readonly share. #17 
   * [x] When the locking user closes the drawing (both, with or without saving), the drawing is unlocked.
* [x] editing through a share
   * [x] Drawing file shared as read-write can be updated.
   * [x] Drawing file in a shared folder can be updated, if the folder is shared rad/write
* [x] view through readonly-share
   * [x] A readonly version of the drawing is renderd. No editing menues appear, on save button is chosen.
* [x] a drawio file uploaded through web or clients can be edited.
   * [x] an error is shown, if a corrupt file was uploaded. -> #7
----

**Comment by jnweiger** [comment]
QA done.
